version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '${MONGODB_PORT}:27017'
    volumes:
      - mongodb_data:/data/db

  redis-timeseries:
    image: redis/redis-stack:latest
    container_name: redis-timeseries
    restart: unless-stopped
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    restart: unless-stopped
    ports:
      - '${KAFKA_PORT}:9092'
    volumes:
      - kafka_data:/var/lib/kafka/data

  elasticsearch:
    image: elasticsearch:9.1.0
    container_name: elasticsearch
    restart: unless-stopped
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    ports:
      - '${ELASTICSEARCH_PORT}:9200'

volumes:
  mongodb_data:
  redis_data:
  kafka_data:
  elasticsearch_data:
